
import type { ColDef, ICellRendererParams, ValueFormatterParams } from 'ag-grid-community';

export const columnDefs: ColDef[] = [
  {
    field: 'id',
    headerName: 'ID',
    width: 70,
    headerTooltip: 'Employee ID',
  },
  {
    headerName: 'Name',
    valueGetter: ({ data }) => `${data.firstName} ${data.lastName}`,
    sortable: true,
    filter: true,
    flex: 1,
    tooltipValueGetter: ({ data }) => `${data.firstName} ${data.lastName}`,
    headerTooltip: 'Full name of the employee',
  },
  {
    field: 'email',
    headerName: 'Email',
    sortable: true,
    filter: true,
    flex: 1.5,
    tooltipField: 'email',
    headerTooltip: 'Official email address',
  },
  {
    field: 'department',
    headerName: 'Department',
    sortable: true,
    filter: true,
    flex: 1,
    tooltipField: 'department',
    headerTooltip: 'Department of the employee',
  },
  {
    field: 'position',
    headerName: 'Position',
    sortable: true,
    filter: true,
    flex: 1,
    tooltipField: 'position',
    headerTooltip: 'Job title or role',
  },
  {
    field: 'salary',
    headerName: 'Salary ($)',
    sortable: true,
    filter: 'agNumberColumnFilter',
    valueFormatter: ({ value }: ValueFormatterParams) =>
      `$${(value as number).toLocaleString()}`,
    flex: 1,
    tooltipValueGetter: ({ value }) => `$${(value as number).toLocaleString()}`,
    headerTooltip: 'Annual salary in USD',
  },
  {
    field: 'hireDate',
    headerName: 'Hire Date',
    sortable: true,
    filter: 'agDateColumnFilter',
    flex: 1,
    tooltipField: 'hireDate',
    headerTooltip: 'Date when the employee joined',
  },
  {
    field: 'age',
    headerName: 'Age',
    sortable: true,
    filter: 'agNumberColumnFilter',
    flex: 0.7,
    tooltipField: 'age',
    headerTooltip: 'Age of the employee',
  },
  {
    field: 'location',
    headerName: 'Location',
    sortable: true,
    filter: true,
    flex: 1,
    tooltipField: 'location',
    headerTooltip: 'Employee work location',
  },
  {
    field: 'performanceRating',
    headerName: 'Rating',
    sortable: true,
    filter: 'agNumberColumnFilter',
    flex: 0.7,
    tooltipField: 'performanceRating',
    headerTooltip: 'Performance score (1-5)',
  },
  {
    field: 'projectsCompleted',
    headerName: 'Projects',
    sortable: true,
    filter: 'agNumberColumnFilter',
    flex: 0.8,
    tooltipField: 'projectsCompleted',
    headerTooltip: 'Number of projects completed',
  },
  {
    field: 'isActive',
    headerName: 'Active',
    cellRenderer: ({ value }: ICellRendererParams) => (value ? '✅' : '❌'),
    sortable: true,
    filter: true,
    width: 100,
    tooltipValueGetter: ({ value }) => (value ? 'Active' : 'Inactive'),
    headerTooltip: 'Is the employee currently active?',
  },
  {
    field: 'manager',
    headerName: 'Manager',
    sortable: true,
    filter: true,
    flex: 1,
    tooltipField: 'manager',
    headerTooltip: 'Reporting manager',
  },
];

export const defaultColDef: ColDef = {
  sortable: true,
  filter: true,
  resizable: true,
  minWidth: 100,
};
